### ISSUE TITLE
In-Kernel Linux Driver is missing.

### ISSUE THREAD

**Issue by light1021** [intel/kvm-sgx#1]
Hi:
The [In-Kernel Linux Driver](https://github.com/jsakkine-intel/linux-sgx.git) is missing. The page returns 404 now. you should update the README file.
Reguards you

**Comment by sean-jc** [comment]
Jarkko's repo will be restored in the very near future, I'll keep this issue open until that time.

**Comment by sean-jc** [comment]
Jarkko's repo is back up, closing.
