### ISSUE TITLE
SGX support for both host and guest OS

### ISSUE THREAD

**Issue by wojciechozga** [intel/kvm-sgx#10]
Are there any plans of enabling SGX in both host and guest OS using kvm-sgx? Currently, when using kvm-sgx, the SGX is inaccessible for enclaves started on the host OS.

**Comment by sean-jc** [comment]
SGX isn't inaccessible, rather EPC assigned to KVM cannot be reclaimed without killing the VM (or suspending it until the EPC can be returned to the VM).  In other words, you can run enclaves in the host, but your effective EPC size will be reduced by whatever amount of EPC is consumed by KVM.

That being said, there are plans to support oversubscribing EPC in KVM.  However, oversubscribing 
a VM without tanking its performance and/or exploding the complexity of the VMM requires additional hardware support to aid in handling EPC conflicts between host and guest.  Platforms with VMM oversubscription functionality are not yet available, which is one of two reasons why software support hasn't been pushed to kvm-sgx, the other being that the current focus is getting SGX and KVM+SGX support into mainline Linux.

**Comment by wojciechozga** [comment]
ok, thank you for your explanation!
