### ISSUE TITLE
In-kernel and out-of-kernel linux driver

### ISSUE THREAD

**Issue by gokhalesushant65** [intel/kvm-sgx#11]
What do you exactly mean by these terms? Usually, to run applications  with SGX, we only need 
1. SDK
2. PSW
3. driver

Also, if my understanding is correct, these drivers are loaded in guest OS, right?

**Comment by sean-jc** [comment]
_in-kernel_ and _out-of-kernel_ refer to the different methods of obtaining/running the driver in the guest OS.  _in-kernel_ means the driver is included in the kernel tree, i.e. is built along with the kernel itself.  _out-of-kernel_ means the driver is standalone and not included in the kernel tree, e.g. you want to run the SGX driver with a stock kernel.

**Comment by sean-jc** [comment]
Updated the README to attempt to clarify the requirements for enabling SGX in a guest.  Let me know if further updates would be helpful.

**Comment by gokhalesushant65** [comment]
Thanks sean.
So, my understanding is there are 2 options:
1. Either recompile your kernel using the 'kvm-sgx' tree or the 'SGX linux development tree'
2. Insert a kernel module using the 'out-of-tree driver'.

Am I right?

**Comment by sean-jc** [comment]
Yep, assuming "your kernel" refers to the guest kernel.

**Comment by maincui** [comment]
@sean-jc,  But what to use if the guest os, like the Azure VM with SGX support, cant be recompiled? is the VM readily enabled for support for other applications? or does it still need driver/sdk/psw for other applications?

**Comment by sean-jc** [comment]
The KVM patches only enable exposing SGX and EPC to a KVM guest, the guest kernel still needs full SGX support.  Ignoring nested virtualization for the moment, these patches are intended to be applied to your host kernel.

**Comment by maincui** [comment]
@sean-jc , thank you very much for upgrading my knowledge of SGX related concepts. Then it means I still have to investigate linux-sgx.
