### ISSUE TITLE
Executing hotcalls in virtualized SGX environment

### ISSUE THREAD

**Issue by gokhalesushant65** [intel/kvm-sgx#13]
Hello,
I want to compile and run application at [this](https://github.com/oweisse/hot-calls) link on virtualized SGX(using kvm-qemu).

Now, regarding some changes to the application:
I have initialized the total iterations to be 10 in 'app.cpp'.

This is completely running fine on host machine with SGX. **Host machine is using ubuntu 18.04.02**

Consider virtualized SGX environment (with KVM and QEMU). **Guest has ubuntu 16.04**.  I am trying to run same 'app' in guest. I get the following output:
[hotcalls_output_in_QEMU_guest.txt](https://github.com/intel/kvm-sgx/files/3034995/hotcalls_output_in_QEMU_guest.txt)

Possibly, its a race condition. Could you let me know how to resolve the issue? My guess is there is some virtualization issue.

**Comment by sean-jc** [comment]
It's extremely unlikely this is a virtualization issue.  Hardware doesn't provide any hooks that allows the host to intercept/modify transitions to/from enclaves, or any other SGX cpl3 operation.  Additional VM-Exits may occur, e.g. EPT violations on initial EPC accesses, but that will simply affect the timing of the guest, or crash it entirely if something goes awry in the host.

More than likely this is a bug in the hotcalls code, e.g. note that the unoptimized calls do not fail.  Looking through the code, none of the variables (except the spinlock) in `typedef struct HotCall` are marked volatile, nor is the struct itself marked volatile.  There are any number of optimizations that could result in incorrect behavior in _HotCall_requestCall()_ or _HotCall_waitForCall()_.
