### ISSUE TITLE
VM SGX and PCI Passthrough

### ISSUE THREAD

**Issue by aamlani** [intel/kvm-sgx#16]
I'm using Ubuntu 16.04 with the 5.0.0+ kernel version. I'm able to successfully launch VMs with SGX support. However, when I try to add a PCI device to the VM, I encounter a "bad address" memory listener initialization error. If I remove the SGX things from the XML, I can do PCI passthrough without a problem. So the problem arises when I try to launch a VM with both SGX and PCI passthrough. I've attached two files. One shows the error I get when trying to launch the VM and the corresponding dmesg output. The other shows the XML I'm using for the SGX and PCI sections. Any guidance would be greatly appreciated.
[error_and_dmesg_output.txt](https://github.com/intel/kvm-sgx/files/4361945/error_and_dmesg_output.txt)
[xml_sections.txt](https://github.com/intel/kvm-sgx/files/4361946/xml_sections.txt)

**Comment by sean-jc** [comment]
I've reproduced this, debug in progress.

**Comment by sean-jc** [comment]
Fixed in Qemu release [sgx-v4.0.0-r2](https://github.com/intel/qemu-sgx/releases/tag/sgx-v4.0.0-r2).
