### ISSUE TITLE
qemu-system-x86_64: unable to find CPU model '+sgx' and Machine option 'epc' requires KVM

### ISSUE THREAD

**Issue by tyxeron** [intel/kvm-sgx#4]
I am currently trying to apply the patches for QEMU and KVM but failing to start a VM with the qemu options "-cpu +sgx" and "-machine epc=<size>", where the first one reports back with "qemu-system-x86_64: unable to find CPU model '+sgx'" and the latter with "Machine option 'epc' requires KVM".

What I did so far is building the custom Kernel from the git repo "https://github.com/intel/kvm-sgx" release "sgx-v4.15.11-r1", with the configration set to include the SGX Core functionality built in and KVM as Module.

I then switched to this kernel and first installed kvm-qemu  aswell as libvirt-clients, libvirt-daemon-system and virt-manager. I build the qemu patches from the release "sgx-v2.11.1-r1" as follows.
   * mkdir build
   * cd build
   * sudo ../configure --prefix=/usr --enable-kvm --enable-seccomp
   * sudo make
   * sudo make install

 After this I tried to test the two options with
  * qemu-system-x86_64 -machine epc=0x1000
  * qemu-system-x86_64 -cpu +sgx

but got above errors

I tried it both on my desktop (Intel(R) Core(TM) i7-7700K) and Laptop (Intel(R) Core(TM) i7-8550U)

**Comment by sean-jc** [comment]
>  the first one reports back with "qemu-system-x86_64: unable to find CPU model '+sgx'"

`+sgx` is just a modifier to the CPU model, you still need to specify a valid model, e.g. Haswell.  That being said, unless you want to run a specific model, using `-cpu host ` to pass-through all host features, including SGX, is the easiest way to get started.

>  and the latter with "Machine option 'epc' requires KVM".

This error occurs if Qemu is built without KVM support, or if KVM is not present in the system.  Do you see any messages prior to the EPC error that might indicate why KVM is not available?

**Comment by tyxeron** [comment]
Thanks for your reply,

Makes sense with the modifier. As for the machine option, I tried it with a '--enable-km' before the '--machine epc=<size>' option and I am able to run the command without errors.
Thanks again!
