### ISSUE TITLE
Launch Qemu with sgx

### ISSUE THREAD

**Issue by jamch21** [intel/kvm-sgx#6]
Hi everyone I am trying to run a guess VM with qemu sgx. I patched the kernel and I am launching my vm using qemu patched. But when I passed the flag sgx ( -cpu +sgx) i get an error the the flag is recognized. What is the correct way to launch the guess VM with sgx support?

**Comment by sean-jc** [comment]
Assuming you have SGX capable hardware, the simplest approach is to do `-cpu host`, which will essentially pass-through the host capabilities unmodified.  The `+sgx` modifier is only useful if you are specifying a particular CPU model, e.g. Haswell, or in the case of `-sgx`, if you want to pass-through the host but without SGX support, e.g. `-cpu host,-sgx`.

**Comment by jamch21** [comment]
Thanks so much. I didnt know the +/- explanation.
