### ISSUE TITLE
Unable to build kvm on Debian Buster 4.16.0

### ISSUE THREAD

**Issue by tyxeron** [intel/kvm-sgx#7]
Hi,

I tried building all three releases on 4.16.0 but it failed.
at `sudo make install -j 4` I get the following error:

`Error! Bad return status for module build on kernel: 4.14.28+ (x86_64)`
`Consult /var/lib/dkms/nvidia-current/390.48/build/make.log for more information.`

The output of make.log is this:

`DKMS make.log for nvidia-current-390.48 for kernel 4.14.28+ (x86_64)`
`Sun Jul  1 16:35:44 CEST 2018`
`make[2]: warning: -jN forced in submake: disabling jobserver mode.`
`Makefile:19: /Kbuild: No such file or directory`
`make[2]: *** No rule to make target '/Kbuild'.  Stop.`

I build kvm-sgx by doing
`sudo make xconfig`
enabling SGX Core and SGX Driver and manually commenting out
`CONFIG_SYSTEM_TRUSTED_KEYRING`
`CONFIG_SYSTEM_BLACKLIST_KEYRING `
in .config and then runing

`sudo make -j 4&& sudo make INSTALL_MOD_STRIP=1 modules_install -j 4 && sudo make install -j 4`

Also I tried before doing anything to copy the config of my kernel by running
`cp /boot/config-$(uname -r) .config` but that did not change a thing.

**Comment by sean-jc** [comment]
Do any of the base kernels, e.g. 4.14.28 without the SGX patches, build with your config?

**Comment by tyxeron** [comment]
I will try this and report back later
